apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-nest-app.fullname" . }}-deployment
  labels:
    {{- include "chart-nest-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart-nest-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:t
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart-nest-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nestApp.containerPort }}
          env:
          - name: MONGO_DB_URL
            valueFrom: 
              secretKeyRef:
                name: nest-app-secrets
                key: mongo-db-url     
