apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-nest-app.fullname" . }}-svc
  labels:
    {{- include "chart-nest-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nestApp.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart-nest-app.selectorLabels" . | nindent 4 }}