apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-mongo-db.fullname" . }}-svc
  labels:
    {{- include "chart-mongo-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mongoDb.containerPort }}
      protocol: TCP
      name: mongo-db
  selector:
    {{- include "chart-mongo-db.selectorLabels" . | nindent 4 }}