apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "chart-mongo-db.fullname" . }}-configmap
data:
  mongo-db-username: {{ .Values.mongoDb.dbUsername }}
  mongo-db-initial-db: {{ .Values.mongoDb.initialDb }}