apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
  namespace: mongo-db
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: mongo-db-configmap
              key: mongo-db-username
        - name: MONGO_INITDB_ROOT_PASSWORD 
          valueFrom: 
            secretKeyRef:
              name: mongo-db-secrets
              key: mongo-db-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:   
            configMapKeyRef:
              name: mongo-db-configmap
              key: mongo-db-initial-db
