apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-app-ingress
  namespace: nest-app
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nest-app-svc
            port:
              number: 3000