apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  namespace: nest-app
  labels:
    app: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-app-container
        image: dominikzawrotny/nest-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_DB_URL
          valueFrom: 
            secretKeyRef:
              name: nest-app-secrets
              key: mongo-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: nest-app-svc
  namespace: nest-app
spec:
  selector:
    app: nest-app
  ports:
  - port: 3000
    targetPort: 3000