apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  labels:
    app: nest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-app-container
        image: dominikzawrotny/nest-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_DB_URL
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-url