apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongodb-password: dG91Z2gyZ3Vlc3M=
    mongodb-url: bW9uZ29kYjovL3Jvb3Q6dG91Z2gyZ3Vlc3NAbG9jYWxob3N0OjI3MDE3L3Rlc3Q=